// hf_config.h -- reads a HuggingFace `config.json` (a flat top-level JSON object of scalar
// fields, plus a few nested/array values this project doesn't need) into an in-memory key/value
// table. Deliberately its own translation unit, never #include'd into qwen_infer.c's plain-
// compiled build unit -- see gguf_load.h's own header comment for the full rationale (unrelated
// code in that TU once changed clang's autovectorization of an unrelated function and produced a
// SIGILL on real hardware; this file follows the identical discipline even though JSON-text
// parsing looks harmless).
//
// Format: a single top-level `{ "key": value, ... }` object. Values this file materializes:
// string, number (stored as double; callers needing an integer cast it), bool, null, and nested
// objects up to depth 1 (e.g. a present `"rope_scaling": {...}` or an index.json's
// `"weight_map": {...}`) via hf_config_get_object(), which returns another HfConfig scoped to
// just that nested object's own fields. Arrays (e.g. `"architectures": [...]`) and objects
// nested deeper than depth 1 are correctly skipped over so parsing can reach later keys, but
// their content is NOT materialized -- hf_config_key_type()/hf_config_has_key() still report
// their presence and type (needed so a caller can FATAL on an unsupported-but-present key,
// rather than silently ignoring it).
//
// SAFETY CONTRACT (mirrors gguf_load.h/safetensors_load.h verbatim): every read is bounds-
// checked against the loaded file's length. A truncated/malformed config.json is a FATAL with a
// specific reason, never a best-effort partial parse -- this reads a file that isn't guaranteed
// to have been generated by this project's own tooling.

#ifndef HF_CONFIG_H
#define HF_CONFIG_H

#include <stdint.h>
#include <stddef.h>

typedef struct HfConfig HfConfig;

typedef enum {
    HF_TYPE_ABSENT = 0,
    HF_TYPE_NULL,
    HF_TYPE_STR,
    HF_TYPE_NUM,
    HF_TYPE_BOOL,
    HF_TYPE_OBJECT,
    HF_TYPE_ARRAY,
} HfValType;

HfConfig *hf_config_open(const char *path);
// Recursively closes every nested HfConfig returned by hf_config_get_object() along the way --
// callers must not separately close a pointer obtained from hf_config_get_object().
void hf_config_close(HfConfig *c);

// Classifies `key`'s JSON value type; HF_TYPE_ABSENT if `key` doesn't exist at this level. Works
// even for an object nested deeper than depth 1 (reports HF_TYPE_OBJECT, just not readable via
// hf_config_get_object() -- check this first if the nesting depth isn't already known).
HfValType hf_config_key_type(const HfConfig *c, const char *key);
// Returns the nested object's own HfConfig scoped to just that object's fields (e.g.
// `rope_scaling`'s leaf fields, or an index.json's `weight_map`). Only objects up to depth 1 are
// materialized -- FATALs if `key` is an object nested deeper than that (no shape found in this
// project needs a grandchild object). FATALs if `key` is present but not an object type. Returns
// NULL if `key` is absent. The returned pointer's lifetime is tied to `c` -- do not close it
// separately (see hf_config_close()).
const HfConfig *hf_config_get_object(const HfConfig *c, const char *key);

// Each getter returns 1 and sets *out if `key` is present with a matching type; returns 0 if
// `key` is absent. FATALs if `key` is present but holds a different JSON value type (a type
// mismatch is a config-file bug worth stopping for, not a "just try the next thing" situation).
int hf_config_get_i64(const HfConfig *c, const char *key, int64_t *out);
int hf_config_get_f64(const HfConfig *c, const char *key, double *out);
int hf_config_get_bool(const HfConfig *c, const char *key, int *out);
// *out_ptr is set to point into this HfConfig's own storage (NUL-terminated, valid until
// hf_config_close) -- caller must not free it.
int hf_config_get_str(const HfConfig *c, const char *key, const char **out_ptr);

// True if `key` exists at the top level, regardless of its value's type (string/number/bool/
// null/array/object) -- the one query that also sees keys whose value this parser doesn't
// materialize.
int hf_config_has_key(const HfConfig *c, const char *key);

// Iterates c's own DIRECT entries (not recursive) by position -- for an object whose leaf keys
// aren't known ahead of time, unlike config.json's fixed field names (e.g. an index.json's
// weight_map, whose keys are tensor names). The returned key is a borrowed pointer into `c`'s
// own storage, valid until hf_config_close(). `i` must be < hf_config_n_entries(c).
size_t hf_config_n_entries(const HfConfig *c);
const char *hf_config_entry_key(const HfConfig *c, size_t i);

#endif // HF_CONFIG_H
