// hf_config.h -- reads a HuggingFace `config.json` (a flat top-level JSON object of scalar
// fields, plus a few nested/array values this project doesn't need) into an in-memory key/value
// table. Deliberately its own translation unit, never #include'd into qwen_infer.c's plain-
// compiled build unit -- see gguf_load.h's own header comment for the full rationale (unrelated
// code in that TU once changed clang's autovectorization of an unrelated function and produced a
// SIGILL on real hardware; this file follows the identical discipline even though JSON-text
// parsing looks harmless).
//
// Format: a single top-level `{ "key": value, ... }` object. Values this file materializes:
// string, number (stored as double; callers needing an integer cast it), bool, null. Nested
// objects/arrays (e.g. `"architectures": [...]`, a present `"rope_scaling": {...}`) are correctly
// skipped over so parsing can reach later keys, but their content is NOT materialized --
// hf_config_has_key() still reports their presence (needed so a caller can FATAL on an
// unsupported-but-present key like `rope_scaling`, rather than silently ignoring it).
//
// SAFETY CONTRACT (mirrors gguf_load.h/safetensors_load.h verbatim): every read is bounds-
// checked against the loaded file's length. A truncated/malformed config.json is a FATAL with a
// specific reason, never a best-effort partial parse -- this reads a file that isn't guaranteed
// to have been generated by this project's own tooling.

#ifndef HF_CONFIG_H
#define HF_CONFIG_H

#include <stdint.h>

typedef struct HfConfig HfConfig;

HfConfig *hf_config_open(const char *path);
void hf_config_close(HfConfig *c);

// Each getter returns 1 and sets *out if `key` is present with a matching type; returns 0 if
// `key` is absent. FATALs if `key` is present but holds a different JSON value type (a type
// mismatch is a config-file bug worth stopping for, not a "just try the next thing" situation).
int hf_config_get_i64(const HfConfig *c, const char *key, int64_t *out);
int hf_config_get_f64(const HfConfig *c, const char *key, double *out);
int hf_config_get_bool(const HfConfig *c, const char *key, int *out);
// *out_ptr is set to point into this HfConfig's own storage (NUL-terminated, valid until
// hf_config_close) -- caller must not free it.
int hf_config_get_str(const HfConfig *c, const char *key, const char **out_ptr);

// True if `key` exists at the top level, regardless of its value's type (string/number/bool/
// null/array/object) -- the one query that also sees keys whose value this parser doesn't
// materialize.
int hf_config_has_key(const HfConfig *c, const char *key);

#endif // HF_CONFIG_H
