-- D-roadmap-4: live role×layer near-tie attribution + closed-loop precision promotion
-- Project: beglin (btdjbfgqzglucifcnuoc)
-- Run once via Supabase MCP (once its project-scope approval lands) or the SQL editor.

create table if not exists moe_neartie_events (
  id bigserial primary key,
  ts timestamptz not null default now(),
  req integer not null,
  pos integer not null,
  predicted_token integer not null,
  competing_token integer not null,
  margin double precision not null,
  model text not null,
  corpus text not null,
  attributed_role text,
  attributed_layer integer
);

create table if not exists moe_role_precision_state (
  role text not null,
  layer integer not null,
  current_bits integer not null default 8,
  event_count integer not null default 0,
  min_margin_observed double precision,
  promoted boolean not null default false,
  promoted_at timestamptz,
  last_updated timestamptz not null default now(),
  primary key (role, layer)
);

create index if not exists moe_neartie_events_ts_idx
  on moe_neartie_events (ts);

-- Real implementation found attribution is one-to-MANY per flagged event (a single real flip
-- routinely gets reproduced by more than one single-role promotion -- pilot data: 13/108 combos
-- for one event), which the original single attributed_role/attributed_layer columns above can't
-- represent. Those columns are kept (harmless, unused) for forward compat with a future per-hit
-- join table; the real accumulation happens here instead, directly on the map -- each attribution
-- hit increments the matching (role,layer) row's event_count. Plain PostgREST UPDATE can't do a
-- read-modify-write increment atomically, hence this RPC.
create or replace function increment_role_precision(p_role text, p_layer integer, p_margin double precision default null)
returns void as $$
  update moe_role_precision_state
  set event_count = event_count + 1,
      min_margin_observed = case
        when p_margin is null then min_margin_observed
        when min_margin_observed is null then p_margin
        else least(min_margin_observed, p_margin)
      end,
      last_updated = now()
  where role = p_role and layer = p_layer;
$$ language sql;

-- Seed: real MOE_ST_ATTN_ROLES_MLA (qwen_infer.c:12311-12316) x NL=27
-- + MOE_ST_DENSE_ROLES (qwen_infer.c:12381-12385) x layer 0 only (FIRST_DENSE_LAYERS=1)
-- + MOE_ST_SHARED_ROLES (qwen_infer.c:12386-12391) x layers 1..26 (MOE_N_SHARED=2>0)
-- + embed_tokens/lm_head wildcards (layer=-1, default bits=32 per moe_role_bits() call sites)
-- 191 rows total (108 attn + 3 dense + 78 shared + 2 wildcard) -- computed, not guessed.
insert into moe_role_precision_state (role, layer, current_bits) values
('q_proj', 0, 8),
('kv_a_proj_with_mqa', 0, 8),
('kv_b_proj', 0, 8),
('o_proj', 0, 8),
('q_proj', 1, 8),
('kv_a_proj_with_mqa', 1, 8),
('kv_b_proj', 1, 8),
('o_proj', 1, 8),
('q_proj', 2, 8),
('kv_a_proj_with_mqa', 2, 8),
('kv_b_proj', 2, 8),
('o_proj', 2, 8),
('q_proj', 3, 8),
('kv_a_proj_with_mqa', 3, 8),
('kv_b_proj', 3, 8),
('o_proj', 3, 8),
('q_proj', 4, 8),
('kv_a_proj_with_mqa', 4, 8),
('kv_b_proj', 4, 8),
('o_proj', 4, 8),
('q_proj', 5, 8),
('kv_a_proj_with_mqa', 5, 8),
('kv_b_proj', 5, 8),
('o_proj', 5, 8),
('q_proj', 6, 8),
('kv_a_proj_with_mqa', 6, 8),
('kv_b_proj', 6, 8),
('o_proj', 6, 8),
('q_proj', 7, 8),
('kv_a_proj_with_mqa', 7, 8),
('kv_b_proj', 7, 8),
('o_proj', 7, 8),
('q_proj', 8, 8),
('kv_a_proj_with_mqa', 8, 8),
('kv_b_proj', 8, 8),
('o_proj', 8, 8),
('q_proj', 9, 8),
('kv_a_proj_with_mqa', 9, 8),
('kv_b_proj', 9, 8),
('o_proj', 9, 8),
('q_proj', 10, 8),
('kv_a_proj_with_mqa', 10, 8),
('kv_b_proj', 10, 8),
('o_proj', 10, 8),
('q_proj', 11, 8),
('kv_a_proj_with_mqa', 11, 8),
('kv_b_proj', 11, 8),
('o_proj', 11, 8),
('q_proj', 12, 8),
('kv_a_proj_with_mqa', 12, 8),
('kv_b_proj', 12, 8),
('o_proj', 12, 8),
('q_proj', 13, 8),
('kv_a_proj_with_mqa', 13, 8),
('kv_b_proj', 13, 8),
('o_proj', 13, 8),
('q_proj', 14, 8),
('kv_a_proj_with_mqa', 14, 8),
('kv_b_proj', 14, 8),
('o_proj', 14, 8),
('q_proj', 15, 8),
('kv_a_proj_with_mqa', 15, 8),
('kv_b_proj', 15, 8),
('o_proj', 15, 8),
('q_proj', 16, 8),
('kv_a_proj_with_mqa', 16, 8),
('kv_b_proj', 16, 8),
('o_proj', 16, 8),
('q_proj', 17, 8),
('kv_a_proj_with_mqa', 17, 8),
('kv_b_proj', 17, 8),
('o_proj', 17, 8),
('q_proj', 18, 8),
('kv_a_proj_with_mqa', 18, 8),
('kv_b_proj', 18, 8),
('o_proj', 18, 8),
('q_proj', 19, 8),
('kv_a_proj_with_mqa', 19, 8),
('kv_b_proj', 19, 8),
('o_proj', 19, 8),
('q_proj', 20, 8),
('kv_a_proj_with_mqa', 20, 8),
('kv_b_proj', 20, 8),
('o_proj', 20, 8),
('q_proj', 21, 8),
('kv_a_proj_with_mqa', 21, 8),
('kv_b_proj', 21, 8),
('o_proj', 21, 8),
('q_proj', 22, 8),
('kv_a_proj_with_mqa', 22, 8),
('kv_b_proj', 22, 8),
('o_proj', 22, 8),
('q_proj', 23, 8),
('kv_a_proj_with_mqa', 23, 8),
('kv_b_proj', 23, 8),
('o_proj', 23, 8),
('q_proj', 24, 8),
('kv_a_proj_with_mqa', 24, 8),
('kv_b_proj', 24, 8),
('o_proj', 24, 8),
('q_proj', 25, 8),
('kv_a_proj_with_mqa', 25, 8),
('kv_b_proj', 25, 8),
('o_proj', 25, 8),
('q_proj', 26, 8),
('kv_a_proj_with_mqa', 26, 8),
('kv_b_proj', 26, 8),
('o_proj', 26, 8),
('dense_gate_proj', 0, 8),
('dense_up_proj', 0, 8),
('dense_down_proj', 0, 8),
('shared_gate_proj', 1, 8),
('shared_up_proj', 1, 8),
('shared_down_proj', 1, 8),
('shared_gate_proj', 2, 8),
('shared_up_proj', 2, 8),
('shared_down_proj', 2, 8),
('shared_gate_proj', 3, 8),
('shared_up_proj', 3, 8),
('shared_down_proj', 3, 8),
('shared_gate_proj', 4, 8),
('shared_up_proj', 4, 8),
('shared_down_proj', 4, 8),
('shared_gate_proj', 5, 8),
('shared_up_proj', 5, 8),
('shared_down_proj', 5, 8),
('shared_gate_proj', 6, 8),
('shared_up_proj', 6, 8),
('shared_down_proj', 6, 8),
('shared_gate_proj', 7, 8),
('shared_up_proj', 7, 8),
('shared_down_proj', 7, 8),
('shared_gate_proj', 8, 8),
('shared_up_proj', 8, 8),
('shared_down_proj', 8, 8),
('shared_gate_proj', 9, 8),
('shared_up_proj', 9, 8),
('shared_down_proj', 9, 8),
('shared_gate_proj', 10, 8),
('shared_up_proj', 10, 8),
('shared_down_proj', 10, 8),
('shared_gate_proj', 11, 8),
('shared_up_proj', 11, 8),
('shared_down_proj', 11, 8),
('shared_gate_proj', 12, 8),
('shared_up_proj', 12, 8),
('shared_down_proj', 12, 8),
('shared_gate_proj', 13, 8),
('shared_up_proj', 13, 8),
('shared_down_proj', 13, 8),
('shared_gate_proj', 14, 8),
('shared_up_proj', 14, 8),
('shared_down_proj', 14, 8),
('shared_gate_proj', 15, 8),
('shared_up_proj', 15, 8),
('shared_down_proj', 15, 8),
('shared_gate_proj', 16, 8),
('shared_up_proj', 16, 8),
('shared_down_proj', 16, 8),
('shared_gate_proj', 17, 8),
('shared_up_proj', 17, 8),
('shared_down_proj', 17, 8),
('shared_gate_proj', 18, 8),
('shared_up_proj', 18, 8),
('shared_down_proj', 18, 8),
('shared_gate_proj', 19, 8),
('shared_up_proj', 19, 8),
('shared_down_proj', 19, 8),
('shared_gate_proj', 20, 8),
('shared_up_proj', 20, 8),
('shared_down_proj', 20, 8),
('shared_gate_proj', 21, 8),
('shared_up_proj', 21, 8),
('shared_down_proj', 21, 8),
('shared_gate_proj', 22, 8),
('shared_up_proj', 22, 8),
('shared_down_proj', 22, 8),
('shared_gate_proj', 23, 8),
('shared_up_proj', 23, 8),
('shared_down_proj', 23, 8),
('shared_gate_proj', 24, 8),
('shared_up_proj', 24, 8),
('shared_down_proj', 24, 8),
('shared_gate_proj', 25, 8),
('shared_up_proj', 25, 8),
('shared_down_proj', 25, 8),
('shared_gate_proj', 26, 8),
('shared_up_proj', 26, 8),
('shared_down_proj', 26, 8),
('embed_tokens', -1, 32),
('lm_head', -1, 32)
on conflict (role, layer) do nothing;
