//
// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
//
// SPDX-License-Identifier: Apache-2.0
//

#include <stdbool.h>
#if !defined(__aarch64__) && !defined(_M_ARM64)
#error This file must be compiled for AArch64.
#else  // Architectural features check.

#include <arm_neon.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include "kai/kai_common.h"
#include "kai_rhs_pack_nxk_qsi4c32ps4s0sf16_qsu4c32s16s0_neon.h"

static const size_t kai_num_bytes_multiplier = sizeof(uint16_t);
static const size_t kai_max_bl = KAI_SME_VEC_LENGTH_MAX_BYTES;
static const size_t kai_nr_tile = 4;
static const size_t kai_bl_multiple_of = 32;
static const float kai_pre_scaled_rhs_scale_factor = 1.0F / 16.0F;

static inline uint8_t kai_get_nibble(const uint8_t* src, const size_t idx, const size_t half) {
    if (idx < half) {
        return src[idx] & 0x0F;
    }
    return (src[idx - half] >> 4) & 0x0F;
}

/// Rearrange one block of source nibbles from K+0/K+bl/2 pairing to K+0/K+4 pairing.
///
/// Source format is generated by pack_data_scales_interleave_block(..., quant_width=bl):
///   src[i] = (K[i + bl/2] << 4) | K[i]  for i = 0 ... (bl/2 - 1)
///
/// Output format is grouped by 8 K-values per packet:
///   packet p covers K[8p...8p+7], encoded as 4 bytes:
///   byte b = low: K[8p+b], high: K[8p+b+4]
///
/// Each output byte is converted from unsigned to signed two's complement
/// via XOR 0x88 (so nibble domain 0..15 becomes -8..7).
static inline void repack_block_k4_signed(uint32_t* dst, const uint8_t* src, const size_t bl) {
    KAI_ASSUME((bl % 32) == 0);
    KAI_ASSUME(bl <= KAI_SME_VEC_LENGTH_MAX_BYTES);
    const size_t half = bl / 2;
    const size_t packets = bl / 8;
    for (size_t p = 0; p < packets; ++p) {
        const size_t k_base = p * 8;
        uint32_t packed_packet = 0;
        for (size_t b = 0; b < 4; ++b) {
            const uint8_t lo = kai_get_nibble(src, k_base + b, half);
            const uint8_t hi = kai_get_nibble(src, k_base + b + 4, half);
            const uint8_t packed_byte = (uint8_t)(((hi << 4) | lo) ^ 0x88U);
            packed_packet |= ((uint32_t)packed_byte << (8 * b));
        }
        dst[p] = packed_packet;
    }
}

static inline uint8x8_t pack_pairs_from_nibbles(const uint8x16_t nibbles) {
    static const uint8_t idx_lo_tbl[8] = {0, 1, 2, 3, 8, 9, 10, 11};
    static const uint8_t idx_hi_tbl[8] = {4, 5, 6, 7, 12, 13, 14, 15};
    const uint8x8_t idx_lo = vld1_u8(idx_lo_tbl);
    const uint8x8_t idx_hi = vld1_u8(idx_hi_tbl);
    const uint8x8_t lo = vqtbl1_u8(nibbles, idx_lo);
    const uint8x8_t hi = vqtbl1_u8(nibbles, idx_hi);
    return vorr_u8(lo, vshl_n_u8(hi, 4));
}

static inline uint16_t load_u16_unaligned(const void* ptr) {
    uint16_t val = 0;
    memcpy(&val, ptr, sizeof(val));
    return val;
}

static inline void convert_s4s0_s16s0_neon(uint32_t* dst_blk, const uint8_t* src_blk, const size_t bl) {
    KAI_ASSUME((bl % kai_bl_multiple_of) == 0);
    KAI_ASSUME(bl <= KAI_SME_VEC_LENGTH_MAX_BYTES);

    const size_t half = bl / 2;
    uint8_t* dst_bytes = (uint8_t*)dst_blk;
    uint8_t* dst_low = dst_bytes;
    uint8_t* dst_high = dst_bytes + (bl / 4);
    const uint8x16_t mask0f = vdupq_n_u8(0x0F);
    const uint8x8_t sign_xor = vdup_n_u8(0x88);

    for (size_t src_off = 0; src_off < half; src_off += 16, dst_low += 8, dst_high += 8) {
        const uint8x16_t src_v = vld1q_u8(src_blk + src_off);
        const uint8x16_t low_nibbles = vandq_u8(src_v, mask0f);
        const uint8x16_t high_nibbles = vshrq_n_u8(src_v, 4);

        uint8x8_t packed = pack_pairs_from_nibbles(low_nibbles);
        packed = veor_u8(packed, sign_xor);
        vst1_u8(dst_low, packed);
        packed = pack_pairs_from_nibbles(high_nibbles);
        packed = veor_u8(packed, sign_xor);
        vst1_u8(dst_high, packed);
    }
}

static inline void convert_s4s0_s16s0_neon_rows4(
    uint32_t* dst0, uint32_t* dst1, uint32_t* dst2, uint32_t* dst3, const uint8_t* src0, const uint8_t* src1,
    const uint8_t* src2, const uint8_t* src3, const size_t bl) {
    KAI_ASSUME((bl % kai_bl_multiple_of) == 0);
    KAI_ASSUME(bl <= KAI_SME_VEC_LENGTH_MAX_BYTES);

    const size_t half = bl / 2;
    uint8_t* dst0_bytes = (uint8_t*)dst0;
    uint8_t* dst1_bytes = (uint8_t*)dst1;
    uint8_t* dst2_bytes = (uint8_t*)dst2;
    uint8_t* dst3_bytes = (uint8_t*)dst3;
    uint8_t* dst0_low = dst0_bytes;
    uint8_t* dst1_low = dst1_bytes;
    uint8_t* dst2_low = dst2_bytes;
    uint8_t* dst3_low = dst3_bytes;
    uint8_t* dst0_high = dst0_bytes + (bl / 4);
    uint8_t* dst1_high = dst1_bytes + (bl / 4);
    uint8_t* dst2_high = dst2_bytes + (bl / 4);
    uint8_t* dst3_high = dst3_bytes + (bl / 4);
    const uint8x16_t mask0f = vdupq_n_u8(0x0F);
    const uint8x8_t sign_xor = vdup_n_u8(0x88);

    for (size_t src_off = 0; src_off < half; src_off += 16) {
        const uint8x16_t src0_v = vld1q_u8(src0 + src_off);
        const uint8x16_t src1_v = vld1q_u8(src1 + src_off);
        const uint8x16_t src2_v = vld1q_u8(src2 + src_off);
        const uint8x16_t src3_v = vld1q_u8(src3 + src_off);

        const uint8x16_t src0_low_n = vandq_u8(src0_v, mask0f);
        const uint8x16_t src1_low_n = vandq_u8(src1_v, mask0f);
        const uint8x16_t src2_low_n = vandq_u8(src2_v, mask0f);
        const uint8x16_t src3_low_n = vandq_u8(src3_v, mask0f);

        const uint8x16_t src0_high_n = vshrq_n_u8(src0_v, 4);
        const uint8x16_t src1_high_n = vshrq_n_u8(src1_v, 4);
        const uint8x16_t src2_high_n = vshrq_n_u8(src2_v, 4);
        const uint8x16_t src3_high_n = vshrq_n_u8(src3_v, 4);

        uint8x8_t packed0 = veor_u8(pack_pairs_from_nibbles(src0_low_n), sign_xor);
        uint8x8_t packed1 = veor_u8(pack_pairs_from_nibbles(src1_low_n), sign_xor);
        uint8x8_t packed2 = veor_u8(pack_pairs_from_nibbles(src2_low_n), sign_xor);
        uint8x8_t packed3 = veor_u8(pack_pairs_from_nibbles(src3_low_n), sign_xor);
        vst1_u8(dst0_low, packed0);
        vst1_u8(dst1_low, packed1);
        vst1_u8(dst2_low, packed2);
        vst1_u8(dst3_low, packed3);

        packed0 = veor_u8(pack_pairs_from_nibbles(src0_high_n), sign_xor);
        packed1 = veor_u8(pack_pairs_from_nibbles(src1_high_n), sign_xor);
        packed2 = veor_u8(pack_pairs_from_nibbles(src2_high_n), sign_xor);
        packed3 = veor_u8(pack_pairs_from_nibbles(src3_high_n), sign_xor);
        vst1_u8(dst0_high, packed0);
        vst1_u8(dst1_high, packed1);
        vst1_u8(dst2_high, packed2);
        vst1_u8(dst3_high, packed3);

        dst0_low += 8;
        dst1_low += 8;
        dst2_low += 8;
        dst3_low += 8;
        dst0_high += 8;
        dst1_high += 8;
        dst2_high += 8;
        dst3_high += 8;
    }
}

static inline void interleave_rows4_u32(
    uint32_t* dst_row_base, const size_t nr, const uint32_t* row0, const uint32_t* row1, const uint32_t* row2,
    const uint32_t* row3, const size_t packets_per_block) {
    KAI_ASSUME(row0 != NULL);
    KAI_ASSUME(row1 != NULL);
    KAI_ASSUME(row2 != NULL);
    KAI_ASSUME(row3 != NULL);
    uint32_t* dst_ptr = dst_row_base;
    for (size_t p = 0; p < packets_per_block; ++p) {
        dst_ptr[0] = row0[p];
        dst_ptr[1] = row1[p];
        dst_ptr[2] = row2[p];
        dst_ptr[3] = row3[p];
        dst_ptr += nr;
    }
}

static inline void store_row_strided_u32(
    uint32_t* dst_block_base, const size_t row_idx, const size_t nr, const uint32_t* src_vals,
    const size_t num_packets) {
    KAI_ASSUME(src_vals != NULL);
    const uint32_t* src_ptr = src_vals;
    uint32_t* dst_ptr = dst_block_base + row_idx;
    size_t remaining = num_packets;
    for (; remaining >= 4; remaining -= 4) {
        dst_ptr[0] = src_ptr[0];
        dst_ptr[nr] = src_ptr[1];
        dst_ptr[2 * nr] = src_ptr[2];
        dst_ptr[3 * nr] = src_ptr[3];
        dst_ptr += 4 * nr;
        src_ptr += 4;
    }
    for (; remaining > 0; --remaining) {
        *dst_ptr = *src_ptr;
        dst_ptr += nr;
        ++src_ptr;
    }
}

inline static size_t kai_num_blocks_per_row(const size_t k, const size_t bl) {
    KAI_ASSUME((bl % 32) == 0);
    KAI_ASSUME((k % 2) == 0);
    return kai_roundup(k, bl) / bl;
}

inline static size_t kai_num_bytes_per_block(const size_t bl) {
    KAI_ASSUME((bl % 32) == 0);
    return (bl / 2) + kai_num_bytes_multiplier;
}

inline static size_t kai_rhs_stride(const size_t k, const size_t bl) {
    KAI_ASSUME((bl % 32) == 0);
    KAI_ASSUME((k % 2) == 0);
    KAI_ASSUME((k % bl) == 0);
    const size_t num_blocks_per_row = kai_num_blocks_per_row(k, bl);
    const size_t num_bytes_per_block = kai_num_bytes_per_block(bl);

    return num_bytes_per_block * num_blocks_per_row;
}

size_t kai_get_rhs_packed_stride_rhs_pack_nxk_qsi4c32ps4s0sf16_qsu4c32s16s0_neon(
    const size_t k,   //
    const size_t nr,  //
    const size_t kr,  //
    const size_t bl) {
    KAI_ASSUME((bl % 32) == 0);
    KAI_ASSUME((k % 2) == 0);
    KAI_ASSUME((k % kr) == 0);
    KAI_ASSUME((k % bl) == 0);
    const size_t num_blocks_per_row = kai_num_blocks_per_row(k, bl);
    const size_t num_bytes_per_block = kai_num_bytes_per_block(bl);

    return nr * (num_bytes_per_block * num_blocks_per_row);
}

size_t kai_get_rhs_offset_rhs_pack_nxk_qsi4c32ps4s0sf16_qsu4c32s16s0_neon(const size_t n_idx, const size_t rhs_stride) {
    return n_idx * rhs_stride;
}

size_t kai_get_rhs_packed_offset_rhs_pack_nxk_qsi4c32ps4s0sf16_qsu4c32s16s0_neon(
    const size_t n_idx,  //
    const size_t k,      //
    const size_t nr,     //
    const size_t kr,     //
    const size_t bl) {
    KAI_ASSUME((bl % 32) == 0);
    KAI_ASSUME((k % 2) == 0);
    KAI_ASSUME((k % kr) == 0);
    KAI_ASSUME((k % bl) == 0);
    KAI_ASSUME((n_idx % nr) == 0);

    return (n_idx / nr) * kai_get_rhs_packed_stride_rhs_pack_nxk_qsi4c32ps4s0sf16_qsu4c32s16s0_neon(k, nr, kr, bl);
}

size_t kai_get_rhs_packed_size_rhs_pack_nxk_qsi4c32ps4s0sf16_qsu4c32s16s0_neon(
    const size_t n,   //
    const size_t k,   //
    const size_t nr,  //
    const size_t kr,  //
    const size_t bl) {
    KAI_ASSUME((bl % 32) == 0);
    KAI_ASSUME((k % 2) == 0);
    KAI_ASSUME((k % kr) == 0);
    KAI_ASSUME((k % bl) == 0);
    const size_t num_rows = kai_roundup(n, nr) / nr;

    return num_rows * kai_get_rhs_packed_stride_rhs_pack_nxk_qsi4c32ps4s0sf16_qsu4c32s16s0_neon(k, nr, kr, bl);
}

void kai_run_rhs_pack_nxk_qsi4c32ps4s0sf16_qsu4c32s16s0_neon(
    const size_t num_groups,   //
    const size_t n,            //
    const size_t k,            //
    const size_t nr,           //
    const size_t kr,           //
    const size_t sr,           //
    const size_t bl,           //
    const uint8_t* rhs,        //
    const float* bias,         //
    void* const rhs_packed,    //
    const size_t extra_bytes,  //
    const struct kai_rhs_pack_qs4cxs1s0_param* params) {
    KAI_ASSUME(num_groups == 1);
    KAI_ASSUME((bl % 32) == 0);
    KAI_ASSUME(bl <= kai_max_bl);
    KAI_ASSUME((k % 2) == 0);
    KAI_ASSUME((k % kr) == 0);
    KAI_ASSUME((k % bl) == 0);
    KAI_ASSUME(bias == NULL);
    KAI_ASSUME(extra_bytes == 0);

    KAI_ASSUME(kr == 4);
    KAI_ASSUME(sr == 2);
    KAI_ASSUME(rhs != NULL);
    KAI_ASSUME(rhs_packed != NULL);
    KAI_ASSUME(params != NULL);
    KAI_ASSUME(params->rhs_zero_point == 8);
    KAI_ASSUME(params->lhs_zero_point == 1);

    const size_t num_blocks = k / bl;
    const size_t rhs_stride = kai_rhs_stride(k, bl);
    const size_t rhs_packed_stride =
        kai_get_rhs_packed_stride_rhs_pack_nxk_qsi4c32ps4s0sf16_qsu4c32s16s0_neon(k, nr, kr, bl);
    const size_t num_bytes_per_block = kai_num_bytes_per_block(bl);
    const size_t packets_per_block = bl / 8;
    const size_t block_stride_u32 = packets_per_block * nr;
    const size_t scales_offset = rhs_packed_stride - (nr * num_blocks * kai_num_bytes_multiplier);

    uint8_t* rhs_packed_ptr = rhs_packed;
    const bool use_fast_path = (kr == 4) && (sr == 2) && ((nr % kai_nr_tile) == 0) && ((bl % kai_bl_multiple_of) == 0);

    if (use_fast_path) {
        uint32_t repacked_rows[4][KAI_SME_VEC_LENGTH_MAX_BYTES / 8] = {0};

        for (size_t group_start = 0; group_start < n; group_start += nr, rhs_packed_ptr += rhs_packed_stride) {
            const size_t rows_in_group = KAI_MIN(n - group_start, nr);
            const uint8_t* rhs_group_base = rhs + group_start * rhs_stride;

            uint32_t* dst_group_base = (uint32_t*)rhs_packed_ptr;
            uint16_t* rhs_packed_scales = (uint16_t*)(rhs_packed_ptr + scales_offset);

            const uint8_t* src_block_base = rhs_group_base;
            uint32_t* dst_block_base = dst_group_base;
            uint16_t* scales_block = rhs_packed_scales;

            for (size_t block_idx = 0; block_idx < num_blocks; ++block_idx) {
                size_t row_idx = 0;
                const uint8_t* src_row_block = src_block_base;

                for (; row_idx + kai_nr_tile <= rows_in_group;
                     row_idx += kai_nr_tile, src_row_block += kai_nr_tile * rhs_stride) {
                    const uint8_t* restrict src_row0 = src_row_block;
                    const uint8_t* restrict src_row1 = src_row0 + rhs_stride;
                    const uint8_t* restrict src_row2 = src_row1 + rhs_stride;
                    const uint8_t* restrict src_row3 = src_row2 + rhs_stride;

                    const uint16_t scale0 = load_u16_unaligned(src_row0);
                    const uint16_t scale1 = load_u16_unaligned(src_row1);
                    const uint16_t scale2 = load_u16_unaligned(src_row2);
                    const uint16_t scale3 = load_u16_unaligned(src_row3);

                    scales_block[row_idx + 0] =
                        kai_cast_f16_f32(kai_cast_f32_f16(scale0) * kai_pre_scaled_rhs_scale_factor);
                    scales_block[row_idx + 1] =
                        kai_cast_f16_f32(kai_cast_f32_f16(scale1) * kai_pre_scaled_rhs_scale_factor);
                    scales_block[row_idx + 2] =
                        kai_cast_f16_f32(kai_cast_f32_f16(scale2) * kai_pre_scaled_rhs_scale_factor);
                    scales_block[row_idx + 3] =
                        kai_cast_f16_f32(kai_cast_f32_f16(scale3) * kai_pre_scaled_rhs_scale_factor);

                    convert_s4s0_s16s0_neon_rows4(
                        repacked_rows[0], repacked_rows[1], repacked_rows[2], repacked_rows[3],
                        src_row0 + kai_num_bytes_multiplier, src_row1 + kai_num_bytes_multiplier,
                        src_row2 + kai_num_bytes_multiplier, src_row3 + kai_num_bytes_multiplier, bl);

                    interleave_rows4_u32(
                        dst_block_base + row_idx, nr, repacked_rows[0], repacked_rows[1], repacked_rows[2],
                        repacked_rows[3], packets_per_block);
                }

                for (; row_idx < rows_in_group; ++row_idx, src_row_block += rhs_stride) {
                    const uint16_t scale = load_u16_unaligned(src_row_block);
                    const uint8_t* blk_src = src_row_block + kai_num_bytes_multiplier;

                    scales_block[row_idx] = kai_cast_f16_f32(kai_cast_f32_f16(scale) * kai_pre_scaled_rhs_scale_factor);

                    convert_s4s0_s16s0_neon(repacked_rows[0], blk_src, bl);
                    store_row_strided_u32(dst_block_base, row_idx, nr, repacked_rows[0], packets_per_block);
                }

                src_block_base += num_bytes_per_block;
                dst_block_base += block_stride_u32;
                scales_block += nr;
            }
        }
        return;
    }

    for (uint64_t n_idx = 0; n_idx < n; n_idx++) {
        uint16_t* rhs_packed_scales =
            (uint16_t*)(rhs_packed_ptr + rhs_packed_stride - (nr * num_blocks * kai_num_bytes_multiplier));

        for (size_t block_idx = 0; block_idx < num_blocks; block_idx++) {
            const uint8_t* blk_base = rhs + (block_idx * num_bytes_per_block) + n_idx * rhs_stride;
            const uint16_t scale = load_u16_unaligned(blk_base);
            const uint8_t* blk_src = blk_base + kai_num_bytes_multiplier;

            // Rearrange full-block nibble pairing:
            // source K[i] + K[i+bl/2] -> packet-local K[j] + K[j+4], then sign map.
            uint32_t repacked[KAI_SME_VEC_LENGTH_MAX_BYTES / 8] = {0};
            repack_block_k4_signed(repacked, blk_src, bl);

            for (size_t packet_idx = 0; packet_idx < packets_per_block; ++packet_idx) {
                ((uint32_t*)rhs_packed_ptr)[(block_idx * packets_per_block + packet_idx) * nr + (n_idx % nr)] =
                    repacked[packet_idx];
            }

            // Pre-divide scale by 16 to compensate lsl/and decode in SME1 kernels.
            const float scale_f32 = kai_cast_f32_f16(scale);
            rhs_packed_scales[(n_idx % nr) + block_idx * nr] =
                kai_cast_f16_f32(scale_f32 * kai_pre_scaled_rhs_scale_factor);
        }

        if (((n_idx + 1) % nr) == 0) {
            rhs_packed_ptr += rhs_packed_stride;
        }
    }
}
#endif  // Architectural features check.
