#!/usr/bin/env python3
"""
Generate a compact, range-encoded Unicode codepoint classification table, matching
llama.cpp's own unicode_cpt_flags scheme (NUMBER=\\p{N}, LETTER=\\p{L}, SEPARATOR=\\p{Z},
ACCENT_MARK=\\p{M}, PUNCTUATION=\\p{P}, SYMBOL=\\p{S}, CONTROL=\\p{C}, plus WHITESPACE as an
orthogonal flag) -- confirmed via direct read of llama.cpp's unicode.h this session.

Source of truth: Python's own unicodedata module (part of CPython's stdlib, itself a direct
implementation of the Unicode Character Database) -- computed once per codepoint 0..0x10FFFF,
then run-length-encoded into (start_codepoint, flags) transition pairs (same encoding shape
llama.cpp's own unicode_ranges_flags uses: std::initializer_list<std::pair<uint32_t,uint16_t>>).

This script both generates the C table AND, before ever emitting it, verifies the RLE encoding
by decoding it back and diffing against the original per-codepoint computation for all 1,114,112
codepoints (0..0x10FFFF) -- exhaustive self-consistency, not sampled, per D-tok-3's own bar.
"""
import unicodedata
import sys

FLAG_UNDEFINED   = 0x0001
FLAG_NUMBER      = 0x0002
FLAG_LETTER      = 0x0004
FLAG_SEPARATOR   = 0x0008
FLAG_ACCENT_MARK = 0x0010
FLAG_PUNCTUATION = 0x0020
FLAG_SYMBOL      = 0x0040
FLAG_CONTROL     = 0x0080
FLAG_WHITESPACE  = 0x0100

CAT_MAJOR_TO_FLAG = {
    'N': FLAG_NUMBER,
    'L': FLAG_LETTER,
    'Z': FLAG_SEPARATOR,
    'M': FLAG_ACCENT_MARK,
    'P': FLAG_PUNCTUATION,
    'S': FLAG_SYMBOL,
    'C': FLAG_CONTROL,
}

MAX_CP = 0x10FFFF

def compute_flags(cp):
    ch = chr(cp)
    cat = unicodedata.category(ch)  # e.g. 'Lu', 'Nd', 'Cc', 'Cn' (unassigned)
    major = cat[0]
    flags = CAT_MAJOR_TO_FLAG.get(major, FLAG_UNDEFINED)
    if ch.isspace():
        flags |= FLAG_WHITESPACE
    return flags

def main():
    print(f"Computing flags for {MAX_CP+1} codepoints...", file=sys.stderr)
    all_flags = [compute_flags(cp) for cp in range(MAX_CP + 1)]

    # Run-length-encode into (start_cp, flags) transition pairs.
    ranges = []
    prev_flags = None
    for cp, flags in enumerate(all_flags):
        if flags != prev_flags:
            ranges.append((cp, flags))
            prev_flags = flags
    print(f"RLE: {len(ranges)} ranges for {MAX_CP+1} codepoints "
          f"({len(ranges)/(MAX_CP+1)*100:.2f}% of naive size)", file=sys.stderr)

    # Exhaustive self-consistency check: decode the ranges back, compare against all_flags.
    def lookup(cp, ranges):
        # binary search: find the last range whose start <= cp
        lo, hi = 0, len(ranges) - 1
        best = 0
        while lo <= hi:
            mid = (lo + hi) // 2
            if ranges[mid][0] <= cp:
                best = mid
                lo = mid + 1
            else:
                hi = mid - 1
        return ranges[best][1]

    mismatches = 0
    # Full exhaustive check would be O(N log N) with binary search per codepoint -- feasible
    # in Python at 1.1M codepoints. Do it for real, not sampled.
    for cp in range(MAX_CP + 1):
        got = lookup(cp, ranges)
        want = all_flags[cp]
        if got != want:
            mismatches += 1
            if mismatches <= 5:
                print(f"MISMATCH cp={cp:#x} got={got:#06x} want={want:#06x}", file=sys.stderr)
    if mismatches:
        print(f"FAIL: {mismatches} mismatches out of {MAX_CP+1} codepoints", file=sys.stderr)
        sys.exit(1)
    print(f"PASS: exhaustive self-consistency check, 0 mismatches across {MAX_CP+1} codepoints",
          file=sys.stderr)

    # Emit the C header.
    out = sys.stdout
    out.write("// unicode_cpt_flags.h -- generated by gen_unicode_table.py (D-tok Phase 2).\n")
    out.write("// Source: Python stdlib unicodedata (CPython %s), run-length-encoded.\n" % (
        unicodedata.unidata_version,))
    out.write("// Exhaustively self-consistency-checked (1,114,112 codepoints, 0 mismatches)\n")
    out.write("// before being emitted -- see gen_unicode_table.py for the generator+checker.\n")
    out.write("// DO NOT HAND-EDIT. Regenerate via: python3 gen_unicode_table.py > unicode_cpt_flags.h\n\n")
    out.write("#ifndef UNICODE_CPT_FLAGS_H\n#define UNICODE_CPT_FLAGS_H\n\n")
    out.write("#include <stdint.h>\n\n")
    out.write("#define UCPT_UNDEFINED   0x0001u\n")
    out.write("#define UCPT_NUMBER      0x0002u  // \\p{N}\n")
    out.write("#define UCPT_LETTER      0x0004u  // \\p{L}\n")
    out.write("#define UCPT_SEPARATOR   0x0008u  // \\p{Z}\n")
    out.write("#define UCPT_ACCENT_MARK 0x0010u  // \\p{M}\n")
    out.write("#define UCPT_PUNCTUATION 0x0020u  // \\p{P}\n")
    out.write("#define UCPT_SYMBOL      0x0040u  // \\p{S}\n")
    out.write("#define UCPT_CONTROL     0x0080u  // \\p{C}\n")
    out.write("#define UCPT_MASK_CATEGORIES 0x00FFu\n")
    out.write("#define UCPT_WHITESPACE  0x0100u\n\n")
    out.write(f"#define UNICODE_CPT_FLAGS_N_RANGES {len(ranges)}\n\n")
    out.write("typedef struct { uint32_t cp; uint16_t flags; } UnicodeCptRange;\n\n")
    out.write("static const UnicodeCptRange UNICODE_CPT_FLAGS_RANGES[UNICODE_CPT_FLAGS_N_RANGES] = {\n")
    for i, (cp, flags) in enumerate(ranges):
        out.write(f"{{0x{cp:06X},0x{flags:04X}}},")
        if (i + 1) % 8 == 0:
            out.write("\n")
    out.write("\n};\n\n")
    out.write("""// Binary search: returns the flags for codepoint cp (0 if cp is somehow out of the table's
// covered range, which shouldn't happen since the first range always starts at cp=0).
static inline uint16_t unicode_cpt_flags(uint32_t cp) {
    int lo = 0, hi = UNICODE_CPT_FLAGS_N_RANGES - 1, best = 0;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (UNICODE_CPT_FLAGS_RANGES[mid].cp <= cp) { best = mid; lo = mid + 1; }
        else hi = mid - 1;
    }
    return UNICODE_CPT_FLAGS_RANGES[best].flags;
}

#endif // UNICODE_CPT_FLAGS_H
""")
    print(f"Emitted C header to stdout.", file=sys.stderr)

if __name__ == "__main__":
    main()
